# http://freenove.com/fnk0085
# Connect to usb near EN/RST, not near BOOT

# https://github.com/Freenove/Freenove_ESP32_S3_WROOM_Board
# https://community.home-assistant.io/t/esp32-s3-wroom-1-n8r8-freenove-camera-board-with-psram-working/815276/2

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2025.7.0
  name_add_mac_suffix: False # this appends to 'name' NOT 'friendly_name'
  on_loop:
    - lambda: |-
        if(id(${id_prefix}wifi_component).is_connected()) {
          if (id(${id_prefix}espcam_update)) {
            id(${id_prefix}espcam).update_camera_parameters();
            if(id(${id_prefix}debug)) { id(${id_prefix}espcam).dump_config(); }
            id(${id_prefix}espcam_update) = false;
          }
        }

  project:
    name: "nliaudat.meter-reader"
    version: "${revision}.dev"
  # platformio_options:
    # build_flags: -DBOARD_HAS_PSRAM -DCORE_DEBUG_LEVEL=0
    # board_build.f_cpu: 240000000L
    # board_build.f_flash: 80000000L
    # board_build.flash_mode: qio
    # board_build.flash_mode: dio
    # board_build.psram_type: opi
    # board_build.memory_type: qio_opi

    # board_build.hwids: 0X303A:0x1001
    # board_connectivity: wifi, bluetooth

    # board_debug.default_tool: esp-builtin
    # board_debug.onboard_tools: esp-builtin
    # board_debug.openocd_target: esp32s3.cfg

    # board_frameworks: arduino, espidf

    # board_name: Freenove ESP32-S3 WROOM N8R8 (8MB Flash / 8MB PSRAM)


substitutions:
  #board and compilation
  board: freenove_esp32_s3_wroom #esp32-s3-devkitc-1 #seeed_xiao_esp32s3 #esp32-s3-devkitc-1 # https://github.com/esphome/issues/issues/4492
  framework: esp-idf #arduino #esp-idf/arduino
  
  #Pin definition
  external_clock_pin: GPIO15
  external_clock_frequency: 20MHz
  i2c_pins_sda: GPIO4
  i2c_pins_scl: GPIO5
  data_pins: [GPIO11, GPIO9, GPIO8, GPIO10, GPIO12, GPIO18, GPIO17, GPIO16] 
  vsync_pin: GPIO6
  href_pin: GPIO7
  pixel_clock_pin: GPIO13
  status_led_pin: GPIO02
  flash_led_pin: GPIO48



esp32:
  board: ${board} 
  # variant: esp32s3 
  # flash_size: 8MB
  framework:
    type: ${framework} 
    version: recommended
    # sdkconfig_options:
      # CONFIG_COMPILER_OPTIMIZATION_SIZE: y
      # CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: "y"
      # CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      # CONFIG_ESP32S3_DATA_CACHE_LINE_64B: "y"
      # CONFIG_ESP32S3_INSTRUCTION_CACHE_32KB: "y"
      # CONFIG_SPIRAM_ALLOW_STACK_EXTERNAL_MEMORY: "y"
      # CONFIG_SPIRAM_TRY_ALLOCATE_WIFI_LWIP: "y"
      # CONFIG_BT_ALLOCATION_FROM_SPIRAM_FIRST: "y"
      # CONFIG_BT_BLE_DYNAMIC_ENV_MEMORY: "y"
      # CONFIG_MBEDTLS_EXTERNAL_MEM_ALLOC: "y"
      # CONFIG_MBEDTLS_SSL_PROTO_TLS1_3: "y"
    
psram:
  mode: octal
  speed: 80MHz
    

  
light:
  - platform: esp32_rmt_led_strip
    rgb_order: GRB
    pin: ${flash_led_pin} #GPIO48
    num_leds: 1
    # rmt_channel: 0 # only for arduino framework
    chipset: ws2812
    name: "flash"
    id: ${id_prefix}flash
    effects:
      - addressable_scan:
          name: "Scan Effect"
          move_interval: 100ms
          scan_width: 1
      - addressable_rainbow:
          name: "Rainbow Effect"
          speed: 10
          width: 50
      - pulse:
          name: "Slow Pulse"
          transition_length: 500ms
          update_interval: 2s
  - platform: status_led
    name: "${name} Status LED"
    id: ${id_prefix}status_led
    icon: "mdi:alarm-light"
    restore_mode: ALWAYS_OFF
    pin: ${status_led_pin}