## https://esphome.io/components/ethernet.html

# spi:
  # clk_pin: ${eth_clk_pin}
  # mosi_pin: ${eth_mosi_pin}
  # miso_pin: ${eth_miso_pin}

# Ethernet Configuration
ethernet:
  type: W5500
  clk_pin: ${eth_clk_pin}
  mosi_pin: ${eth_mosi_pin}
  miso_pin: ${eth_miso_pin}
  cs_pin: ${eth_cs_pin}
  interrupt_pin: ${eth_int_pin}
  reset_pin: GPIO0
  
  # Optional manual IP
  # manual_ip:
    # static_ip: 192.168.1.164
    # gateway: 192.168.1.2
    # subnet: 255.255.255.0
  

  
